# Generated by Django 4.0.3 on 2022-11-28 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobileVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('employee_number', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('id1', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ('id1',),
            },
        ),
        migrations.CreateModel(
            name='ServiceAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, null=True)),
                ('owner_name', models.CharField(max_length=66)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('reason', models.CharField(max_length=50)),
                ('finished', models.BooleanField(blank=True, default=False, null=True)),
                ('vip', models.BooleanField(default=False, null=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to='service_rest.technician')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=21, null=True, unique=True)),
                ('titulo', models.CharField(max_length=66)),
                ('descripcion', models.CharField(max_length=66)),
                ('enlace', models.URLField(null=True)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='service_rest.tipo')),
            ],
        ),
    ]
