# Generated by Django 4.0.3 on 2022-11-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_remove_formulariocliente_tipo_delete_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('id1', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ('id1',),
            },
        ),
    ]
