# Generated by Django 4.0.3 on 2022-11-28 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariocliente',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='service_rest.tipo'),
        ),
    ]
