# Generated by Django 4.0.3 on 2022-11-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_formulariocliente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='abbreviation',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
