# Generated by Django 4.0.3 on 2022-11-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariocliente',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
