# Generated by Django 4.0.3 on 2022-11-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_tipo_abbreviation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='tipo',
            old_name='id1',
            new_name='id',
        ),
    ]
